### ISSUE TITLE
部署时之后访问后台时出现错误：

### ISSUE THREAD

**Issue by userliujianjian** [liangliangyy/DjangoBlog#124]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1308, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/__init__.py", line 101, in mail_admins
    mail.send(fail_silently=fail_silently)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 122, in _send
    from_email = sanitize_address(email_message.from_email, encoding)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/message.py", line 119, in sanitize_address
    address = Address(nm, addr_spec=addr)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/email/headerregistry.py", line 42, in __init__
    a_s, rest = parser.get_addr_spec(addr_spec)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/email/_header_value_parser.py", line 1988, in get_addr_spec
    token, value = get_local_part(value)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/email/_header_value_parser.py", line 1800, in get_local_part
    if value[0] in CFWS_LEADER:
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1308, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/__init__.py", line 101, in mail_admins
    mail.send(fail_silently=fail_silently)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 122, in _send
    from_email = sanitize_address(email_message.from_email, encoding)
  File "/home/webui/.pyenv/versions/3.5.1/envs/wy/lib/python3.5/site-packages/django/core/mail/message.py", line 119, in sanitize_address
    address = Address(nm, addr_spec=addr)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/email/headerregistry.py", line 42, in __init__
    a_s, rest = parser.get_addr_spec(addr_spec)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/email/_header_value_parser.py", line 1988, in get_addr_spec
    token, value = get_local_part(value)
  File "/home/webui/.pyenv/versions/3.5.1/lib/python3.5/email/_header_value_parser.py", line 1800, in get_local_part
    if value[0] in CFWS_LEADER:
IndexError: string index out of range

**Comment by liangliangyy** [comment]
将`DEBUG=True`，然后去掉log中的mail_admins配置试下

**Comment by userliujianjian** [comment]
已解决，是由于自身配置缺失的原因造成的，非常感谢您的提示！





| |
刘健健
邮箱：sxliujianjian@163.com
|

签名由 网易邮箱大师 定制

在2018年05月26日 11:40，车亮亮 写道：

将DEBUG=True，然后去掉log中的mail_admins配置试下
