### ISSUE TITLE
按照配置文件来,出错了,没找到解决办法

### ISSUE THREAD

**Issue by Dongscode** [liangliangyy/DjangoBlog#128]
(blog-github-demo) ➜  DjangoBlog ./manage.py makemigrations      
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 10, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 11, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 9, in <module>
    from .loader import MigrationLoader
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/db/migrations/loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder:
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 22, in MigrationRecorder
    class Migration(models.Model):
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/home/yb/桌面/Django-demo/blog-github-demo/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by ywfluctier** [comment]
我也有这个问题。
当初看教程的时候，
做到在views.py中导入同级的models.py的类时候出现了问题
`from .modes import ClassName`

注释掉这句代码就没有AppRegistryNotReadyError了，但不是从根本上解决。

我注意到这个django博客中也用到了上述代码，但为何能直接通过呢？

**Comment by ywfluctier** [comment]
我在stackoverflow上看到了相关讨论，
有人建议在导入models.py的数据库模型之间先运行django.setup()，发现挺管用。可以试试插入如下代码
`import django`
`django.setup()`

**Comment by liangliangyy** [comment]
抱歉，你的这个问题我没有遇到过，请排查下`INSTALLED_APPS `是否有加入你创建的app，或者你使用的django版本是否是否支持依赖的别的包版本，或者model名称也可能会导致这样的错误。
希望能对你有帮助，

**Comment by DongshanSpaces** [comment]
OK ,我试试

**Comment by ywfluctier** [comment]
ASASD
