### ISSUE TITLE
为什么你的python文件中没有# coding=utf-8

### ISSUE THREAD

**Issue by liu2510865** [liangliangyy/DjangoBlog#203]
我下载下来执行报编码错误，请问怎么统一处理？
还有那个下载文件包中的很多包 并没有最新的版本哦

**Comment by liangliangyy** [comment]
你好，编码错误是哪里报的呢，请贴下详细的错误信息，另外关于新版本的包我会定期更新并做测试之后才会升级的。

**Comment by liu2510865** [comment]
pymysql.err.InternalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')
之前的错误我解决了是我Python 版本的问题 现在数据库迁移有这个错误

`mwdeMacBook:DjangoBlog mw$ ./manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, blog, comments, contenttypes, oauth, owntracks, servermanager, sessions, sites
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying accounts.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying blog.0001_initial...Traceback (most recent call last):
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/mw/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')

The above exception was the direct cause of the following exception:`

**Comment by liu2510865** [comment]
问题我已经解决了，多谢。
