### ISSUE TITLE
创建超级用户时编码报错

### ISSUE THREAD

**Issue by YipCyun** [liangliangyy/DjangoBlog#233]
你好，在创建超级用户时，提示：
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/venv/DjangoBlog/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/venv/DjangoBlog/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/venv/DjangoBlog/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/venv/DjangoBlog/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/home/venv/DjangoBlog/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/venv/DjangoBlog/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 112, in handle
    username = self.get_input_data(self.username_field, input_msg, default_username)
  File "/home/venv/DjangoBlog/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 193, in get_input_data
    raw_value = input(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

数据库的中djangoblog库的编码已设置为utf8mb4，系统为Ubuntu，已迁移数据表，不知道是不是因为python版本为3.5.2导致的问题呢，谢谢！

**Comment by YipCyun** [comment]
将settings.py中的语言改为'en-us'，就不会报错了，是不是因为python版本导致的呢？

**Comment by liangliangyy** [comment]
你是创建用户的时候用户名或密码有特殊字符吗? 或者是有中文?

**Comment by YipCyun** [comment]
> 你是创建用户的时候用户名或密码有特殊字符吗? 或者是有中文?

不是，我是运行./manage.py createsuperuser的时候它就直接报错了，还没到我输入的这一步。
然后我修改了settings里的语言配置改成en-us后，这个错误就消失了。按道理来说python3.5已经unicode支持了，所以才不解为什么会报错。

**Comment by liangliangyy** [comment]
Django是什么版本？
