### ISSUE TITLE
部署报错：AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by czxin788** [liangliangyy/DjangoBlog#276]
(blog) [root@adminset DjangoBlog-7.0]# python --version
Python 3.6.0

(blog) [root@adminset DjangoBlog-7.0]# python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 103, in handle
    loader.check_consistent_history(connection)
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/migrations/loader.py", line 281, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/backends/base/base.py", line 193, in connect
    conn_params = self.get_connection_params()
  File "/usr/local/pyEnvs/blog/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 201, in get_connection_params
    if settings_dict['HOST'].startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by liangliangyy** [comment]
请参考readme中的说明
https://github.com/liangliangyy/DjangoBlog#%E8%BF%90%E8%A1%8C
数据库配置是否修改了?

**Comment by czxin788** [comment]
![image](https://user-images.githubusercontent.com/13861904/58956927-2418d580-87d2-11e9-8e03-63d5ac682619.png)

修改了，不知我修改的对吗

**Comment by czxin788** [comment]
可以了，知道怎么回事。
![image](https://user-images.githubusercontent.com/13861904/58957195-b7eaa180-87d2-11e9-9506-1f22109d560d.png)
