### ISSUE TITLE
windows安装依赖时报错

### ISSUE THREAD

**Issue by BruceLee569** [liangliangyy/DjangoBlog#337]
Win10系统安装rcssmin这个包时，显示错误如下：
```
Building wheels for collected packages: rcssmin
  Building wheel for rcssmin (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\辰冢\\AppData\\Local\\Temp\\pip-install-u5q3mgmp\\rcssmin\\setup.py'"'"'; __file__='"'"'C:\\Users\\辰冢\\AppData\\Local\\Temp\\pip-install-u5q3mgmp\\rcssmin\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ 辰冢\AppData\Local\Temp\pip-wheel-u3hssz74' --python-tag cp37
       cwd: C:\Users\辰冢\AppData\Local\Temp\pip-install-u5q3mgmp\rcssmin\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying .\rcssmin.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_rcssmin' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for rcssmin
  Running setup.py clean for rcssmin
Failed to build rcssmin
ERROR: spyder 3.3.6 requires pyqt5<5.13; python_version >= "3", which is not installed.
ERROR: spyder 3.3.6 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
```
网上查了下，可以通过以下命令单独安装rcssmin，成功：
```
pip install rcssmin --install-option="--without-c-extensions"
```

**Comment by CAU-LiuZiyu** [comment]
@liangliangyy 你好！win10环境下安装依赖报错：

`ERROR: Command errored out with exit status 1:
     command: 'd:\Anaconda3\envs\Python_3.8\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-n9m8nkw8\\django-mdeditor\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-n9m8nkw8\\django-mdeditor\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-install-n9m8nkw8\django-mdeditor\pip-egg-info'
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-n9m8nkw8\django-mdeditor\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-n9m8nkw8\django-mdeditor\setup.py", line 5, in <module>
        long_description = readme.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 167: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

不太明白这个错误是什么意思，该怎么解决呢？

**Comment by lemonYZ** [comment]
这个问题我没有遇到过，不过看起来应该是在某个源码那里默认的编码是gbk,试试加上 encoding='utf-8'，看看行不行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CAU-LiuZiyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月5日(星期天) 下午5:04
收件人:&nbsp;"liangliangyy/DjangoBlog"<DjangoBlog@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [liangliangyy/DjangoBlog] windows安装依赖时报错 (#337)





 
@liangliangyy 你好！win10环境下安装依赖报错：
 
ERROR: Command errored out with exit status 1: command: 'd:\Anaconda3\envs\Python_3.8\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-n9m8nkw8\\django-mdeditor\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-n9m8nkw8\\django-mdeditor\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-install-n9m8nkw8\django-mdeditor\pip-egg-info' cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-n9m8nkw8\django-mdeditor\ Complete output (5 lines): Traceback (most recent call last): File "<string&gt;", line 1, in <module&gt; File "C:\Users\Administrator\AppData\Local\Temp\pip-install-n9m8nkw8\django-mdeditor\setup.py", line 5, in <module&gt; long_description = readme.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 167: illegal multibyte sequence ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 
不太明白这个错误是什么意思，该怎么解决呢？

**Comment by wudih146** [comment]
我用pip安装compressor 也是提示这个错误，发现Microsoft Visual C++ Build Tools 2015这个的高版本是安装了的，卸载重装也不行。然后按照网上给的方法安装rcssmin 添加个参数"--without-c-extensions"也不行，把高版本的卸载后奇迹般的装好了 #
