### ISSUE TITLE
访问主页多次有一定几率出现502错误

### ISSUE THREAD

**Issue by Woooosz** [liangliangyy/DjangoBlog#34]
报错信息如下：貌似是session读写问题
```
[2017-09-29 09:07:01 +0800] [26953] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/ENV/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/ENV/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/wwwroot/newBlog/DjangoBlog/urls.py", line 45, in <module>
    url(r'', include('servermanager.urls', namespace='servermanager', app_name='servermanagers'))
  File "/root/ENV/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/ENV/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/wwwroot/newBlog/servermanager/urls.py", line 18, in <module>
    from .robot import robot
  File "/home/wwwroot/newBlog/servermanager/robot.py", line 36, in <module>
    robot.config['SESSION_STORAGE'] = FileStorage(filename='werobot_session')
  File "/root/ENV/python3/lib/python3.5/site-packages/werobot/session/filestorage.py", line 23, in __init__
    self.db = dbm.open(filename, "c")
  File "/usr/local/lib/python3.5/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ENV/python3/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/root/ENV/python3/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/root/ENV/python3/lib/python3.5/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/root/ENV/python3/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/ENV/python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/ENV/python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/ENV/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/wwwroot/newBlog/DjangoBlog/urls.py", line 45, in <module>
    url(r'', include('servermanager.urls', namespace='servermanager', app_name='servermanagers'))
  File "/root/ENV/python3/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/ENV/python3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/wwwroot/newBlog/servermanager/urls.py", line 18, in <module>
    from .robot import robot
  File "/home/wwwroot/newBlog/servermanager/robot.py", line 36, in <module>
    robot.config['SESSION_STORAGE'] = FileStorage(filename='werobot_session')
  File "/root/ENV/python3/lib/python3.5/site-packages/werobot/session/filestorage.py", line 23, in __init__
    self.db = dbm.open(filename, "c")
  File "/usr/local/lib/python3.5/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable
```

**Comment by Woooosz** [comment]
我刚刚读了代码，分析了一下
我决定先安装一个memcache看看能否解决问题

**Comment by liangliangyy** [comment]
这个是session的问题.应该是存在werobot_session这个文件,然后尝试读取他作为session存储的时候出现错误.装memcache然后修改下配置是可以解决的.我这两天处理下这个问题.
