### ISSUE TITLE
搭建成功后新增文章报错

### ISSUE THREAD

**Issue by RooterN** [liangliangyy/DjangoBlog#392]
DoesNotExist at /admin/blog/article/add/
Site matching query does not exist.
我搭建好后，其他都没问题，但是通过管理进入新增文章，开启debug后，总是报这个错误，能指导下看哪块代码吗？现在还没参透

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [●] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [●] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [●] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ●] 请求技术支持

**Comment by liangliangyy** [comment]
你好，请贴下详细一点等错误信息。
另外可以检查下有没有添加site。

**Comment by RooterN** [comment]
> 你好，请贴下详细一点等错误信息。
> 另外可以检查下有没有添加site。

您好，报错如下：

DoesNotExist at /admin/blog/article/add/
Site matching query does not exist.
Request Method:	GET
Request URL:	http://www.xxxx.com/admin/blog/article/add/
Django Version:	3.0.4
Exception Type:	DoesNotExist
Exception Value:	
Site matching query does not exist.
Exception Location:	/root/python/env/djangoblog/lib/python3.6/site-packages/django/db/models/query.py in get, line 417
Python Executable:	/root/python/env/djangoblog/bin/python3
Python Version:	3.6.9
Python Path:	
['/root/python/env/djangoblog/bin',
 '/root/python/DjangoBlog',
 '/root/python/env/djangoblog/lib/python36.zip',
 '/root/python/env/djangoblog/lib/python3.6',
 '/root/python/env/djangoblog/lib/python3.6/lib-dynload',
 '/usr/lib/python3.6',
 '/root/python/env/djangoblog/lib/python3.6/site-packages']
Server time:	星期日, 5 四月 2020 16:36:51 +0800
++++++++++++++++++++++++++++++++++++++++
Environment:


Request Method: GET
Request URL: http://www.xxxx.com/admin/blog/article/add/

Django Version: 3.0.4
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'mdeditor',
 'haystack',
 'blog',
 'accounts',
 'comments',
 'oauth',
 'servermanager',
 'owntracks',
 'compressor']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.http.ConditionalGetMiddleware',
 'blog.middleware.OnlineMiddleware']



Traceback (most recent call last):
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1632, in _changeform_view
    return self.render_change_form(request, context, add=add, change=not add, obj=obj, form_url=form_url)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1116, in render_change_form
    view_on_site_url = self.get_view_on_site_url(obj)
  File "/root/python/DjangoBlog/blog/admin.py", line 92, in get_view_on_site_url
    site = get_current_site().domain
  File "/root/python/DjangoBlog/DjangoBlog/utils.py", line 64, in news
    value = func(*args, **kwargs)
  File "/root/python/DjangoBlog/DjangoBlog/utils.py", line 131, in get_current_site
    site = Site.objects.get_current()
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/sites/models.py", line 58, in get_current
    return self._get_site_by_id(site_id)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/python/env/djangoblog/lib/python3.6/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name

Exception Type: DoesNotExist at /admin/blog/article/add/
Exception Value: Site matching query does not exist.

**Comment by liangliangyy** [comment]
你需要在后台先添加site配置

**Comment by RooterN** [comment]
> 你需要在后台先添加site配置

您好，site应该是已经增加了的
![image](https://user-images.githubusercontent.com/16112686/78780159-be3c4200-79d0-11ea-8d46-9a9f2bdaedda.png)

**Comment by liangliangyy** [comment]
参考这里：
https://github.com/liangliangyy/DjangoBlog/blob/3e7063e9102093c897de5492cdf3399c67f6bf2b/DjangoBlog/settings.py#L199

这里会获取siteid=1的，你可以修改成你自己的siteid。

**Comment by RooterN** [comment]
> 参考这里：
> https://github.com/liangliangyy/DjangoBlog/blob/3e7063e9102093c897de5492cdf3399c67f6bf2b/DjangoBlog/settings.py#L199
> 
> 这里会获取siteid=1的，你可以修改成你自己的siteid。
感谢，已经修改，并测试成功
