### ISSUE TITLE
USE_TZ=True时 logentry功能无法使用

### ISSUE THREAD

**Issue by abcdelf** [liangliangyy/DjangoBlog#463]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

----

# 调试环境
1. master分支，macos环境，系统时区是shanghai，mysql的时区是system。数据库中记录的时间戳也是utc的。

2. 已参考该博文：https://www.cnblogs.com/yy3b2007com/p/7601940.html  ，
将setting中的USE_TZ = True设置为false的话，可以正常打开，设置为false之后，mysql中保存的时间戳就是utc+8的了。

# 以下是具体的报错信息：
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/admin/logentry/

Django Version: 3.2.2
Python Version: 3.8.8
Installed Applications:
['django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'mdeditor',
 'haystack',
 'blog',
 'accounts',
 'comments',
 'oauth',
 'servermanager',
 'owntracks',
 'compressor']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.http.ConditionalGetMiddleware',
 'blog.middleware.OnlineMiddleware']


Template error:
In template /opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/contrib/admin/templates/admin/base.html, error at line 44
   Database returned an invalid datetime value. Are time zone definitions for your database installed?
   34 :         </div>
   35 :         {% block usertools %}
   36 :         {% if has_permission %}
   37 :         <div id="user-tools">
   38 :             {% block welcome-msg %}
   39 :                 {% translate 'Welcome,' %}
   40 :                 <strong>{% firstof user.get_short_name user.get_username %}</strong>.
   41 :             {% endblock %}
   42 :             {% block userlinks %}
   43 :                 {% if site_url %}
   44 :                      <a href="{{ site_url } }">{% translate 'View site' %}</a> /
   45 :                 {% endif %}
   46 :                 {% if user.is_active and user.is_staff %}
   47 :                     {% url 'django-admindocs-docroot' as docsroot %}
   48 :                     {% if docsroot %}
   49 :                         <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
   50 :                     {% endif %}
   51 :                 {% endif %}
   52 :                 {% if user.has_usable_password %}
   53 :                 <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
   54 :                 {% endif %}


Traceback (most recent call last):
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/contrib/admin/templatetags/admin_list.py", line 379, in date_hierarchy
    'choices': [{
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/db/models/query.py", line 171, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1122, in apply_converters
    value = converter(value, expression, connection)
  File "/opt/anaconda3/envs/DjangoBlog/lib/python3.8/site-packages/django/db/models/functions/datetime.py", line 248, in convert_value
    raise ValueError(

Exception Type: ValueError at /admin/admin/logentry/
Exception Value: Database returned an invalid datetime value. Are time zone definitions for your database installed?

```

**Comment by liangliangyy** [comment]
参考：
https://stackoverflow.com/questions/21351251/database-returned-an-invalid-value-in-queryset-dates

**Comment by abcdelf** [comment]
> 参考：
> 
> https://stackoverflow.com/questions/21351251/database-returned-an-invalid-value-in-queryset-dates

好的，我明天试一下，谢谢🤓

**Comment by abcdelf** [comment]
macos下面可以用下面的命令更新一下mysql
```shell
mysql_tzinfo_to_sql /usr/share/zoneinfo > zone_import.sql
cat zone_import.sql | mysql -u root mysql -p
mysql -u root mysql -p
	select CONVERT_TZ(now(), 'UTC', 'Asia/Shanghai');
mysql -u root -p -e "flush tables;" mysql
```
