### ISSUE TITLE
command报错

### ISSUE THREAD

**Issue by fengzifrank** [liangliangyy/DjangoBlog#54]
老哥您好 运行你的项目  
Error fetching command 'ping_baidu': cannot import name 'COMMAND'
Command 'ping_baidu' skipped
这个错误困扰了我一天   pip  install command 也安装了  还是没有解决

**Comment by liangliangyy** [comment]
你好`pip install -Ur requirements.txt ` 这个操作执行了吗?
报错是在执行什么命令的时候出现的呢?
另外麻烦贴下详细点的错误信息.

**Comment by fengzifrank** [comment]
Traceback (most recent call last):
  File "E:\pycharm\PyCharm 2017.1.2\helpers\pycharm\django_manage.py", line 43, in <module>
    run_module(manage_file, None, '__main__', True)
  File "D:\python3.5\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "D:\python3.5\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\python3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:/beifeng/pythonwork/djblog\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\python3.5\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "D:\python3.5\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\python3.5\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\python3.5\lib\site-packages\django\core\management\base.py", line 327, in execute
    self.check()
  File "D:\python3.5\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\python3.5\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "D:\python3.5\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\python3.5\lib\site-packages\django\core\checks\model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "D:\python3.5\lib\site-packages\django\db\models\base.py", line 1284, in check
    errors.extend(cls._check_fields(**kwargs))
  File "D:\python3.5\lib\site-packages\django\db\models\base.py", line 1359, in _check_fields
    errors.extend(field.check(**kwargs))
  File "D:\python3.5\lib\site-packages\django\db\models\fields\__init__.py", line 913, in check
    errors = super(AutoField, self).check(**kwargs)
  File "D:\python3.5\lib\site-packages\django\db\models\fields\__init__.py", line 219, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "D:\python3.5\lib\site-packages\django\db\models\fields\__init__.py", line 322, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "D:\python3.5\lib\site-packages\django\db\backends\mysql\validation.py", line 49, in check_field
    field_type = field.db_type(self.connection)
  File "D:\python3.5\lib\site-packages\django\db\models\fields\__init__.py", line 644, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "D:\python3.5\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\python3.5\lib\site-packages\django\db\backends\mysql\base.py", line 174, in data_types
    if self.features.supports_microsecond_precision:
  File "D:\python3.5\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\python3.5\lib\site-packages\django\db\backends\mysql\features.py", line 53, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "D:\python3.5\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\python3.5\lib\site-packages\django\db\backends\mysql\base.py", line 385, in mysql_version
    with self.temporary_connection() as cursor:
  File "D:\python3.5\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "D:\python3.5\lib\site-packages\django\db\backends\base\base.py", line 591, in temporary_connection
    cursor = self.cursor()
  File "D:\python3.5\lib\site-packages\django\db\backends\base\base.py", line 254, in cursor
    return self._cursor()
  File "D:\python3.5\lib\site-packages\django\db\backends\base\base.py", line 229, in _cursor
    self.ensure_connection()
  File "D:\python3.5\lib\site-packages\django\db\backends\base\base.py", line 213, in ensure_connection
    self.connect()
  File "D:\python3.5\lib\site-packages\django\db\backends\base\base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\python3.5\lib\site-packages\django\db\backends\mysql\base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "D:\python3.5\lib\site-packages\MySQLdb\__init__.py", line 85, in Connect
    from MySQLdb.connections import Connection
  File "D:\python3.5\lib\site-packages\pymysql\connections.py", line 20, in <module>
    from .constants import CLIENT, COMMAND, CR, FIELD_TYPE, SERVER_STATUS
ImportError: cannot import name 'COMMAND'


具体报错是这个  老哥

**Comment by liangliangyy** [comment]
pip install -Ur requirements.txt 这个操作执行了吗

**Comment by fengzifrank** [comment]
执行了

**Comment by fengzifrank** [comment]
Successfully installed Django-1.11.7 Pillow-4.3.0 certifi-2017.11.5 coverage-4.4.1 django-haystack-2.6.1 idna-2.6 jieba-0.39 markdown2-2.3.5 mistune-0.8.1 pytz-2017.3 requests-2.18.4 six-1.11.0 sqlparse-0.2.4 urllib3-1.22

**Comment by liangliangyy** [comment]
感觉有点像是 PyMySQL 的原因, 你要不然试试新建一个虚拟环境 然后激活之后安装下依赖再试试.

**Comment by fengzifrank** [comment]
嗯嗯  我回去试试 老哥

**Comment by LoveDoze** [comment]
我也遇见了这个问题，这个pip install -Ur requirements.txt命令就执行不了 不知道为什么会这样，博主，或者题住可不可以给解答一下

**Comment by LoveDoze** [comment]
错误提示是这样：Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by LoveDoze** [comment]
博主 我这也遇到这个问题了，我这个报错信息是：[2018-12-22 14:48:44,952] INFO [DjangoBlog.utils.news:62 utils] cache_decorator set cache:get_current_site key:ed66f18092b6d8ebff620a185728e3fd
Error fetching command 'ping_baidu': (1146, "Table 'djangoblog.django_site' doesn't exist")
Command 'ping_baidu' skipped
Error fetching command 'build_solr_schema': The 'solr' backend requires the installation of 'pysolr'. Please refer to the documentation.
Command 'build_solr_schema' skipped
