### ISSUE TITLE
docker 部署后，容器自动退出

### ISSUE THREAD

**Issue by Li-CW** [liangliangyy/DjangoBlog#560]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [x] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [x] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

---
docker 部署项目，我拉取镜像后，执行下面命令：（修改了mysql的ip和密码）。
容器启动后，马上自己exited.
```bash
docker run -itd  -p 8000:8000 -e DJANGO_MYSQL_HOST=我mysql的ip -e DJANGO_MYSQL_PASSWORD=我mysql的密码 -e DJANGO_MYSQL_USER=root -e DJANGO_MYSQL_DATABASE=djangoblog --name djangoblog liangliangyy/djangoblog:latest

//docker ps -a 后如下输出
7d661b9ffae0   liangliangyy/djangoblog:latest   "/code/djangoblog/bi…"   5 seconds ago   Exited (1) 1 second ago
```
请问我时哪里配置错了吗？

**Comment by Li-CW** [comment]
mysql服务器能用sqlyog连通

**Comment by liangliangyy** [comment]
你好，可以使用如下命令来尝试看看输出是什么：
```
docker run -it  -p 8000:8000 -e DJANGO_MYSQL_HOST=我mysql的ip -e DJANGO_MYSQL_PASSWORD=我mysql的密码 -e DJANGO_MYSQL_USER=root -e DJANGO_MYSQL_DATABASE=djangoblog --name djangoblog liangliangyy/djangoblog:latest
```

**Comment by Li-CW** [comment]
您好，输出信息如下：
```bash
Starting djangoblog as root                                                                             
/code/djangoblog/bin/docker_start.sh: line 14: cd: /code/djangoBlog: No such file or directory          
Migrations for 'owntracks':                                                                             
  owntracks/migrations/0001_initial.py                                                                  
    - Create model OwnTrackLog                                                                          
Migrations for 'servermanager':                                                                         
  servermanager/migrations/0001_initial.py                                                              
    - Create model commands                                                                             
    - Create model EmailSendLog                                                                         
Migrations for 'accounts':                                                                              
  accounts/migrations/0001_initial.py                                                                   
    - Create model BlogUser                                                                             
Migrations for 'blog':                                                                                  
  blog/migrations/0001_initial.py                                                                       
    - Create model BlogSettings                                                                         
    - Create model Links                                                                                
    - Create model SideBar                                                                              
    - Create model Tag                                                                                  
    - Create model Category                                                                             
    - Create model Article                                                                              
Migrations for 'comments':             
  comments/migrations/0001_initial.py                                                                   
    - Create model Comment                                                                              
Migrations for 'oauth':                                                                                 
  oauth/migrations/0001_initial.py                                                                      
    - Create model OAuthConfig                                                                          
    - Create model OAuthUser                                                                            
Operations to perform:                                                                                  
  Apply all migrations: accounts, admin, auth, blog, comments, contenttypes, oauth, owntracks, serverman
ager, sessions, sites                                                                                   
Running migrations:                                                                                     
  No migrations to apply.                                                                               
Traceback (most recent call last):                                                                      
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute      
    return self.cursor.execute(sql, params)                                                             
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute  
    return self.cursor.execute(query, args)                                                             
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute               
    res = self._query(query)                                                                            
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query                
    db.query(q)                                                                                         
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query             
    _mysql.connection.query(self, query)                                                                
MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xE7\\xBD\\x91\\xE7\\xAB\\x99...
' for column 'name' at row 1")      
he above exception was the direct cause of the following exception:                                    

Traceback (most recent call last):                  
  File "/code/djangoblog/manage.py", line 22, in <module>                                               
    execute_from_command_line(sys.argv)                                                                 
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execut
e_from_command_line       
    utility.execute()                               
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execut
e                         
    self.fetch_command(subcommand).run_from_argv(self.argv)                                             
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_a
rgv                       
    self.execute(*args, **cmd_options)                                                                  
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)                                                              
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)                                                                  
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 268, i
n handle                  
    emit_post_migrate_signal(                       
  File "/usr/local/lib/python3.10/site-packages/django/core/management/sql.py", line 42, in emit_post_mi
grate_signal              
    models.signals.post_migrate.send(                                                                   
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
       return [                                        
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))                                           
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/__init__.py", line 83, in
 create_permissions       
    Permission.objects.using(using).bulk_create(perms)                                                  
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 514, in bulk_create
    returned_columns = self._batched_insert(                                                            
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1293, in _batched_inser
t                         
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)                                
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute
_sql                      
    cursor.execute(sql, params)                     
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)                                                                 
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_
wrappers                  
    return executor(sql, params, many, context)                                                         
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
     return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xE7\\xBD\\x91\\xE7\\xAB\\x99...' for column 'name' at row 1")

```
