### ISSUE TITLE
pip install requirements.txt时mysqlclient报错

### ISSUE THREAD

**Issue by ahuaiph** [liangliangyy/DjangoBlog#626]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [DjangoBlog的readme](https://github.com/liangliangyy/DjangoBlog/blob/master/README.md)
- [ ] [配置说明](https://github.com/liangliangyy/DjangoBlog/blob/master/bin/config.md)
- [ ] [其他 Issues](https://github.com/liangliangyy/DjangoBlog/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
安装依赖`pip3 install -r requirements.txt`时，安装到mysqlclient报错，报错信息如下：

```
Collecting mysqlclient==2.1.1
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/50/5f/eac919b88b9df39bbe4a855f136d58f80d191cfea34a3dcf96bf5d8ace0a/mysqlclient-2.1.1.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.1/88.1 kB 11.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: mysql_config: command not found
      /bin/sh: mariadb_config: command not found
      /bin/sh: mysql_config: command not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3q1d_aqr/mysqlclient_b7af980a3268489188c1a8383b69edf1/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-3q1d_aqr/mysqlclient_b7af980a3268489188c1a8383b69edf1/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-3q1d_aqr/mysqlclient_b7af980a3268489188c1a8383b69edf1/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

请问该怎么处理呢？

**Comment by liangliangyy** [comment]
参考：https://pypi.org/project/mysqlclient/

**Comment by qianjiangchao1992** [comment]
换成pymysql

**Comment by sxchou** [comment]
下载本地安装

**Comment by tkyztshouhou** [comment]
Linux
Note that this is a basic step. I can not support complete step for build for all environment. If you can see some error, you should fix it by yourself, or ask for support in some user forum. Don't file a issue on the issue tracker.

You may need to install the Python 3 and MySQL development headers and libraries like so:

$ sudo apt-get install python3-dev default-libmysqlclient-dev build-essential # Debian / Ubuntu
% sudo yum install python3-devel mysql-devel # Red Hat / CentOS
Then you can install mysqlclient via pip now:

$ pip install mysqlclient
