### ISSUE TITLE
windows上可以安装所有的包，但是centos7上 pip install -Ur requirements.txt 报错：Preparing metadata (pyproject.toml) ... error；

### ISSUE THREAD

**Issue by Tine789** [liangliangyy/DjangoBlog#665]
麻烦懂的大佬解答下呀
[tine@Tine DjangoBlog]$ pip install -Ur requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: coverage==7.2.2 in /home/tine/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (7.2.2)
Requirement already satisfied: bleach==6.0.0 in /home/tine/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (6.0.0)
Requirement already satisfied: Django==4.2.1 in /home/tine/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (4.2.1)
Requirement already satisfied: django-compressor==4.3.1 in /home/tine/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.3.1)
Collecting django-haystack==3.2.1 (from -r requirements.txt (line 5))
  Using cached django-haystack-3.2.1.tar.gz (466 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info
      writing /tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info/SOURCES.txt'
      listing git files failed - pretending there aren't any
      reading manifest file '/tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      adding license file 'AUTHORS'
      writing manifest file '/tmp/pip-modern-metadata-k7fcysyn/django_haystack.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-k7fcysyn/django_haystack-3.2.1.dist-info'
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 16, in <module>
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 104, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-q7fcyxru/overlay/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by power5845** [comment]
这个错误表明在安装 django-haystack 时出现了问题，可能与缺少某些构建依赖项有关。下面是一些建议的解决方法：
1.**安装构建工具： 确保你的系统上安装了构建工具，例如 build-essential（对于Ubuntu/Debian系统）或 gcc。**
`sudo apt-get install build-essential`
2.**安装Python开发工具： 如果你是在Linux系统上运行，确保安装了Python开发工具。**
`sudo apt-get install python3-dev`
3.**安装C编译器： 确保你的系统上有C编译器，这在某些情况下可能是缺失的。**
`sudo apt-get install gcc`
4.**尝试直接安装Haystack： 如果以上步骤不起作用，可以尝试直接安装 django-haystack 而不使用 requirements.txt 文件。**
`pip install django-haystack==3.2.1`
5.**检查Python版本： 确保你使用的是与 django-haystack 兼容的Python版本。有时，特定版本的库可能需要特定版本的Python。**

尝试这些方法中的一个或多个，看看是否能够解决你遇到的问题。
