### ISSUE TITLE
pagedown 找不到此模板？

### ISSUE THREAD

**Issue by Freen247** [liangliangyy/DjangoBlog#96]
```
C:\Users\asus\Desktop\DjangoBlog>python manage.py makemigtations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pagedown'
```
pagedown模板 在哪被使用？我在所有文件中查询词条也没找到。
另外 我是win10系统

**Comment by liangliangyy** [comment]
```
pip install -Ur requirements.txt
```
成功执行了吗?

**Comment by Freen247** [comment]
Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
这是问题

**Comment by Freen247** [comment]
‘好像是因为Django2.0不支持pagedown模块了’？

**Comment by liangliangyy** [comment]
其实win下可以试试wheel安装：
```
pip install wheel

pip install rcssmin --install-option="--without-c-extensions"
pip install rjsmin --install-option="--without-c-extensions"
```

参考：
https://github.com/TabbycatDebate/tabbycat/issues/265
