### ISSUE TITLE
    if value[0] in CFWS_LEADER: IndexError: string index out of range

### ISSUE THREAD

**Issue by Freen247** [liangliangyy/DjangoBlog#99]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1442, in _log
    self.handle(record)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 863, in handle
    self.emit(record)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\mail\__init__.py", line 101, in mail_admins
    mail.send(fail_silently=fail_silently)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\mail\message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\mail\backends\smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\mail\backends\smtp.py", line 122, in _send
    from_email = sanitize_address(email_message.from_email, encoding)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\mail\message.py", line 119, in sanitize_address
    address = Address(nm, addr_spec=addr)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\email\headerregistry.py", line 42, in __init__
    a_s, rest = parser.get_addr_spec(addr_spec)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\email\_header_value_parser.py", line 1583, in get_addr_spec
    token, value = get_local_part(value)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36\lib\email\_header_value_parser.py", line 1395, in get_local_part
    if value[0] in CFWS_LEADER:
IndexError: string index out of range
```
本地网页打不开了

**Comment by Freen247** [comment]
runserver 后显示
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
但是打开网页 才报错，是不是文件里面哪里检索或者循环出问题了？

**Comment by liangliangyy** [comment]
将settings.py中的DEBUG=False修改为DEBUG=True
试试看.

**Comment by Freen247** [comment]
为嘛子 不用django2.0.4呢。

**Comment by liangliangyy** [comment]
暂时还没升级
